### ISSUE TITLE
GL-AR300M16无法启动openclash

### ISSUE THREAD

**Issue by prinswift** [xddcore/SoftRouter#1]
我按照你的教程代码刷入了openclash，在配置完后启动报错，如图所示
![DSC_0995](https://user-images.githubusercontent.com/75475260/146287741-a4f87845-8399-4d65-8623-faea8c76da4c.JPG)
![mmexport1639553694688](https://user-images.githubusercontent.com/75475260/146287764-fd13e974-e1cf-4e1f-ab85-ae6d844044ea.png)

**Comment by xddcore** [comment]
看OpenClash的log，应该是libcap和libcap-bin的依赖有问题，可以检查下这两个依赖是否存在。如不存在，则你可以手动打开.sh文件，看一下里面的libcap和libcap-bin依赖下载链接是否能够正常打开。可以尝试手动安装这两个依赖。另外关于libcap和libcap-bin应注意版本号相同。

**Comment by prinswift** [comment]
我就是看文件里面一条条输入的，链接是正常的，也安装上去了，内核版本也没错，我后来也重新下载下来重新装过，但还是碰到这个问题，醉了。



---原始邮件---
发件人: "Chengsen ***@***.***&gt;
发送时间: 2021年12月16日(周四) 下午4:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xddcore/SoftRouter] GL-AR300M16无法启动openclash (Issue #1)




 
看OpenClash的log，应该是libcap和libcap-bin的依赖有问题，可以检查下这两个依赖是否存在。如不存在，则你可以手动打开.sh文件，看一下里面的libcap和libcap-bin依赖下载链接是否能够正常打开。可以尝试手动安装这两个依赖。另外关于libcap和libcap-bin应注意版本号相同。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by prinswift** [comment]
我看你之前写用的是2.48的，我现在自动安装的是2.51，你能不能把2.48的发给我试试？我谷歌搜不到



---原始邮件---
发件人: "Chengsen ***@***.***&gt;
发送时间: 2021年12月16日(周四) 下午4:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xddcore/SoftRouter] GL-AR300M16无法启动openclash (Issue #1)




 
看OpenClash的log，应该是libcap和libcap-bin的依赖有问题，可以检查下这两个依赖是否存在。如不存在，则你可以手动打开.sh文件，看一下里面的libcap和libcap-bin依赖下载链接是否能够正常打开。可以尝试手动安装这两个依赖。另外关于libcap和libcap-bin应注意版本号相同。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xddcore** [comment]
> 我看你之前写用的是2.48的，我现在自动安装的是2.51，你能不能把2.48的发给我试试？我谷歌搜不到
> […](#)
> ---原始邮件--- 发件人: "Chengsen ***@***.***&gt; 发送时间: 2021年12月16日(周四) 下午4:58 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [xddcore/SoftRouter] GL-AR300M16无法启动openclash (Issue #1) 看OpenClash的log，应该是libcap和libcap-bin的依赖有问题，可以检查下这两个依赖是否存在。如不存在，则你可以手动打开.sh文件，看一下里面的libcap和libcap-bin依赖下载链接是否能够正常打开。可以尝试手动安装这两个依赖。另外关于libcap和libcap-bin应注意版本号相同。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xddcore** [comment]
您好，您需要的依赖我这里也没有了。我目前主要还是用MT1300比较多一些。
