### ISSUE TITLE
我运行dash install_openclash_for_official.sh提示 -ash: dash: not found

### ISSUE THREAD

**Issue by designer-fanfan** [xddcore/SoftRouter#2]
你好，运行命令提示-ash: dash: not found，不知道怎么解决，求助。使用的是官方固件，ssh连接，然后运行

**Comment by xddcore** [comment]
1. 您好，官方固件里面没有dash。您可直接`./install_openclash_for_official_MT1300.sh`运行自动安装脚本。
2. 另外在安装libcap以及libcap-bin依赖时，可能会提示未找到。这是由于我在编写脚本时，所wget的依赖版本相较于现在过老。而libcap和libcap-bin版本一直在更新所导致的。您可以修改脚本中相关的wget操作的链接或手动安装libcap和libcap-bin来解决此问题。
